# Generated by Django 3.1.1 on 2020-12-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20201229_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='added_by',
            field=models.IntegerField(max_length=10),
        ),
    ]
