# Generated by Django 3.1.1 on 2020-12-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20201229_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='picture',
        ),
        migrations.AlterField(
            model_name='friend',
            name='added_by',
            field=models.IntegerField(default=4),
        ),
    ]
