# Generated by Django 3.1.1 on 2020-12-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20201229_1606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
