# Generated by Django 3.1.1 on 2021-01-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_auto_20201229_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
