# Generated by Django 3.1.1 on 2021-01-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_auto_20210102_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
