# Generated by Django 3.1.1 on 2021-01-02 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0014_profilefriend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='picture',
        ),
        migrations.AddField(
            model_name='friend',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend',
            name='email',
            field=models.EmailField(max_length=55),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.DeleteModel(
            name='ProfileFriend',
        ),
    ]
