# Generated by Django 3.1.5 on 2021-02-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_auto_20210102_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefriend',
            name='image',
        ),
    ]
