# Generated by Django 3.1.5 on 2021-02-02 15:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0017_remove_profilefriend_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFriend',
            new_name='EmployeeDetail',
        ),
    ]
